version: 2.1
workflows:
  main:
    jobs:
      - build
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run: |
          docker create -v /app/test2 --name terratest alpine:3.4 /bin/true
          ls -l .
          docker cp test terratest:/app/test2
          docker run --volumes-from terratest seanson/terratest-helm-tester:latest go test -v ./test2/...
