version: 2.1
workflows:
  main:
    jobs:
      - build
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run: |
          docker build . -t terratest-helm-tester:local
          docker create -v /app/test2 --name test_source alpine:3.4 /bin/true
          docker cp charts terratest:/app/test2
          docker run --name terratest --volumes-from test_source terratest-helm-tester:local ./test2/...
          docker cp terratest:/app/out ./test_results
      - store_test_results:
          path: ./test_results
